# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_protos.protos import dockermsg_pb2 as grpc__protos_dot_protos_dot_dockermsg__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grpc_protos/protos/dockermsg_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DockerAgentStub(object):
    """服务端

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.images = channel.unary_unary(
                '/dockermsg.DockerAgent/images',
                request_serializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Req_DockerImages.SerializeToString,
                response_deserializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Rsp_DockerImages.FromString,
                _registered_method=True)
        self.pull_images = channel.unary_unary(
                '/dockermsg.DockerAgent/pull_images',
                request_serializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Req_DockerPull.SerializeToString,
                response_deserializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Rsp_DockerPull.FromString,
                _registered_method=True)
        self.container_up = channel.unary_unary(
                '/dockermsg.DockerAgent/container_up',
                request_serializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Req_DockerUp.SerializeToString,
                response_deserializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Rsp_DockerUp.FromString,
                _registered_method=True)
        self.container_down = channel.unary_unary(
                '/dockermsg.DockerAgent/container_down',
                request_serializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Req_DockerDown.SerializeToString,
                response_deserializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Rsp_DockerDown.FromString,
                _registered_method=True)
        self.container_restart = channel.unary_unary(
                '/dockermsg.DockerAgent/container_restart',
                request_serializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Req_DockerRestart.SerializeToString,
                response_deserializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Rsp_DockerRestart.FromString,
                _registered_method=True)
        self.container_rollback = channel.unary_unary(
                '/dockermsg.DockerAgent/container_rollback',
                request_serializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Req_DockerRollBack.SerializeToString,
                response_deserializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Rsp_DockerRollBack.FromString,
                _registered_method=True)
        self.container_info = channel.unary_unary(
                '/dockermsg.DockerAgent/container_info',
                request_serializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Req_DockerInfo.SerializeToString,
                response_deserializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Rsp_DockerInfo.FromString,
                _registered_method=True)


class DockerAgentServicer(object):
    """服务端

    """

    def images(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def pull_images(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def container_up(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def container_down(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def container_restart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def container_rollback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def container_info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DockerAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'images': grpc.unary_unary_rpc_method_handler(
                    servicer.images,
                    request_deserializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Req_DockerImages.FromString,
                    response_serializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Rsp_DockerImages.SerializeToString,
            ),
            'pull_images': grpc.unary_unary_rpc_method_handler(
                    servicer.pull_images,
                    request_deserializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Req_DockerPull.FromString,
                    response_serializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Rsp_DockerPull.SerializeToString,
            ),
            'container_up': grpc.unary_unary_rpc_method_handler(
                    servicer.container_up,
                    request_deserializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Req_DockerUp.FromString,
                    response_serializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Rsp_DockerUp.SerializeToString,
            ),
            'container_down': grpc.unary_unary_rpc_method_handler(
                    servicer.container_down,
                    request_deserializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Req_DockerDown.FromString,
                    response_serializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Rsp_DockerDown.SerializeToString,
            ),
            'container_restart': grpc.unary_unary_rpc_method_handler(
                    servicer.container_restart,
                    request_deserializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Req_DockerRestart.FromString,
                    response_serializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Rsp_DockerRestart.SerializeToString,
            ),
            'container_rollback': grpc.unary_unary_rpc_method_handler(
                    servicer.container_rollback,
                    request_deserializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Req_DockerRollBack.FromString,
                    response_serializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Rsp_DockerRollBack.SerializeToString,
            ),
            'container_info': grpc.unary_unary_rpc_method_handler(
                    servicer.container_info,
                    request_deserializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Req_DockerInfo.FromString,
                    response_serializer=grpc__protos_dot_protos_dot_dockermsg__pb2.Rsp_DockerInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dockermsg.DockerAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dockermsg.DockerAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DockerAgent(object):
    """服务端

    """

    @staticmethod
    def images(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dockermsg.DockerAgent/images',
            grpc__protos_dot_protos_dot_dockermsg__pb2.Req_DockerImages.SerializeToString,
            grpc__protos_dot_protos_dot_dockermsg__pb2.Rsp_DockerImages.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def pull_images(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dockermsg.DockerAgent/pull_images',
            grpc__protos_dot_protos_dot_dockermsg__pb2.Req_DockerPull.SerializeToString,
            grpc__protos_dot_protos_dot_dockermsg__pb2.Rsp_DockerPull.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def container_up(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dockermsg.DockerAgent/container_up',
            grpc__protos_dot_protos_dot_dockermsg__pb2.Req_DockerUp.SerializeToString,
            grpc__protos_dot_protos_dot_dockermsg__pb2.Rsp_DockerUp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def container_down(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dockermsg.DockerAgent/container_down',
            grpc__protos_dot_protos_dot_dockermsg__pb2.Req_DockerDown.SerializeToString,
            grpc__protos_dot_protos_dot_dockermsg__pb2.Rsp_DockerDown.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def container_restart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dockermsg.DockerAgent/container_restart',
            grpc__protos_dot_protos_dot_dockermsg__pb2.Req_DockerRestart.SerializeToString,
            grpc__protos_dot_protos_dot_dockermsg__pb2.Rsp_DockerRestart.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def container_rollback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dockermsg.DockerAgent/container_rollback',
            grpc__protos_dot_protos_dot_dockermsg__pb2.Req_DockerRollBack.SerializeToString,
            grpc__protos_dot_protos_dot_dockermsg__pb2.Rsp_DockerRollBack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def container_info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dockermsg.DockerAgent/container_info',
            grpc__protos_dot_protos_dot_dockermsg__pb2.Req_DockerInfo.SerializeToString,
            grpc__protos_dot_protos_dot_dockermsg__pb2.Rsp_DockerInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
